version: '3.8'

services:
  backend:
    build:
      context: github.com/EMZemskova/server_go
      dockerfile: Dockerfile  
    container_name: server_go
    ports:
      - "8080:8080"  
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - DB_NAME=postgres

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data  
    ports:
      - "5432:5432" 

volumes:
  pgdata: